/**
 * Generate src/generated/version.ts at build/dev time.
 *
 * Captures:
 *   - SemVer from package.json   (declared release version)
 *   - git commit (short + full)  (exact code identity)
 *   - branch                     (which branch produced this build)
 *   - dirty flag                 (uncommitted changes — should be off in prod)
 *   - build time (ISO)           (when this artefact was produced)
 *
 * Falls back gracefully when git isn't available (CI without .git, container
 * with --depth=0). All env-var overrides win — useful for CI to inject the
 * authoritative SHA when builds happen in detached-head state.
 *
 *   AKPILOT_VERSION_OVERRIDE     -> overrides the entire computed version
 *   AKPILOT_COMMIT_OVERRIDE      -> overrides git short SHA
 *   AKPILOT_COMMIT_FULL_OVERRIDE -> overrides full SHA
 *   AKPILOT_BRANCH_OVERRIDE      -> overrides branch
 *
 * Version is auto-bumped: package.json's MAJOR.MINOR is kept, but the patch
 * is replaced with the commit count on the current HEAD's history. So every
 * new commit produces a monotonically-increasing version like 0.1.79 → 0.1.80
 * without manual bumps.
 *
 * Usage: `npx tsx scripts/generate-version.ts` (run by `prebuild` / `predev`).
 */
import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");

function tryGit(args: string): string {
  try {
    return execSync(`git ${args}`, { cwd: repoRoot, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return "";
  }
}

const pkg = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf-8")) as { version?: string };

/**
 * Compute MAJOR.MINOR.{commit-count}. MAJOR and MINOR come from package.json
 * (so a deliberate release can still bump them); the patch is derived from
 * git so it auto-increments per commit. Falls back to package.json verbatim
 * when git isn't reachable (shallow CI checkout, no .git in container, etc.).
 */
function computeVersion(): string {
  if (process.env.AKPILOT_VERSION_OVERRIDE) return process.env.AKPILOT_VERSION_OVERRIDE;
  const base = pkg.version ?? "0.0.0";
  const m = base.match(/^(\d+)\.(\d+)/);
  if (!m) return base;
  const count = tryGit("rev-list --count HEAD");
  if (!/^\d+$/.test(count)) return base;
  return `${m[1]}.${m[2]}.${count}`;
}
const version = computeVersion();
const commit =
  process.env.AKPILOT_COMMIT_OVERRIDE ?? tryGit("rev-parse --short HEAD") ?? "unknown";
const commitFull =
  process.env.AKPILOT_COMMIT_FULL_OVERRIDE ?? tryGit("rev-parse HEAD") ?? "unknown";
const branch =
  process.env.AKPILOT_BRANCH_OVERRIDE ?? tryGit("rev-parse --abbrev-ref HEAD") ?? "unknown";
// Clean working tree? `git status --porcelain` returns empty if no changes.
const dirty = tryGit("status --porcelain").length > 0;
const buildTime = new Date().toISOString();

const outPath = join(repoRoot, "src/generated/version.ts");
mkdirSync(dirname(outPath), { recursive: true });
const content = `/* AUTO-GENERATED by scripts/generate-version.ts. Do not edit by hand. */
export const VERSION = ${JSON.stringify(version)};
export const COMMIT = ${JSON.stringify(commit || "unknown")};
export const COMMIT_FULL = ${JSON.stringify(commitFull || "unknown")};
export const BRANCH = ${JSON.stringify(branch || "unknown")};
export const DIRTY = ${dirty ? "true" : "false"};
export const BUILD_TIME = ${JSON.stringify(buildTime)};

export interface VersionInfo {
  version: string;
  commit: string;
  commitFull: string;
  branch: string;
  dirty: boolean;
  buildTime: string;
}

export const versionInfo: VersionInfo = {
  version: VERSION,
  commit: COMMIT,
  commitFull: COMMIT_FULL,
  branch: BRANCH,
  dirty: DIRTY,
  buildTime: BUILD_TIME,
};
`;
writeFileSync(outPath, content);
console.log(
  `version.ts: ${version} · ${commit}${dirty ? "+dirty" : ""} · ${branch} · ${buildTime}`,
);
